import SatisfyingCursor from '@/assets/Cursor';
import type { Metadata } from 'next';
import '../globals.css';
import { Header } from '@/widgets/header/Header';
import { Footer } from '@/widgets/footer/Footer';

export const metadata: Metadata = {
  title: 'GOLU3STUDIO',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SatisfyingCursor />
        <div className="max-w-[1220px] w-full mx-auto px-[20px]">
          <Header />
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
